spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev #开发环境
    application:
        name: dept-dev
---
spring:
    profiles: dev #测试环境
    application:
        name: dept-test

#切记保存为utf-8格式