spring:
    profiles:
        active:
        - dev
--- 
server:
  port: 8005
mybatis:
  type-aliases-package: com.yu.study.entities      
  mapper-locations:
    - classpath: mybatis/mapper/**/*.xml         
spring:
  profiles: dev
  application:
    name: dept                             
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:          
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept8001
    prefer-ip-address: true 
info:
  app.name: yu-cloud-dept8001
  company-name: www.yu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
--- 